application: jurassic-perts
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: jurassic_perts.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: lxml
  version: "2.3"

# http://stackoverflow.com/questions/33665274/python-typeerror-when-receiving-server-response
env_variables:
  GAE_USE_SOCKETS_HTTPLIB : '1'

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^.*bower\_components$
- ^.*node\_modules$
- ^sass$
- ^generate.py$  # Causes I/O issues if included